### PR TITLE
Adding the option to add cutom marks. (Works with next)

### PR DESCRIPTION
**Pull request by Greenscreener**

### CODE REVIEW

**Comment by Greenscreener** [comment]
So, it now works. It was actually just a matter of triggering the resize event. If you have any complaints, please tell me. As you can see, I can sometimes fix them.

**Comment by Greenscreener** [comment]
Oh yeah. The problem is, that I test using rawgit, so I have to commit to see the changes, even though I did something wrong.

**Comment by FHRNet** [comment]
* Make sure everything works fine BEFORE doing a PR!  
* Pretty unusable on mobile, "+" button is extremely small. Also, it doesn't have to be an "input", could easily be a "button" element. Bakalari uses Jquery UI, so it could look pretty good: https://jqueryui.com/button/#default

**Review by FHRNet — CHANGES_REQUESTED** [review]
Why are you using `&quot;` everywhere? That doesn't make any sense.

**Comment by Greenscreener** [comment]
So, I actually used `<button>` but it reloaded the page every time.
And I use `&quot;` because I'm too deep in quotes to use both `"` and `'`. If there is a better way, tell me please, I've always done it this way and if it's wrong, I don't want to do that anymore.

**Comment by Greenscreener** [comment]
I now use a `<button>` (it was reloading, beacuse I used it wrong). Also scaled the button up to fill the entire space between the inputs.

**Comment by Greenscreener** [comment]
How do you request a review?

**Comment by FHRNet** [comment]
How about escaping?  
`jQuery(".znamky").prepend("<div class='znamka-v' data-clasif=\"{'vaha':0,'MarkText':'0'}\"")…`

**Comment by Greenscreener** [comment]
Oh, yeah. Forgot about that.

**Comment by FHRNet** [comment]
Did you test this? Unfortunately, this does not seem to work. I've got the quotes backwards in my example above, seems like you did the same mistake.  
`jQuery(".znamky").append("<div class='znamka-v' data-clasif='{\"vaha\":0,\"MarkText\":0}'>…</div>")`

**Comment by Greenscreener** [comment]
Oh. JSON doesn't accept single quotes.

**Comment by Greenscreener** [comment]
Now, I tested it and it works.

**Review by FHRNet — APPROVED** [review]

**Pull request merged**
